"""add columns

Revision ID: 16a7079c1f19
Revises: b5f0e0559a34
Create Date: 2023-09-06 11:12:27.858922+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a7079c1f19'
down_revision = 'b5f0e0559a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
