"""add columns

Revision ID: caeb376180e0
Revises: 2c5e28ff2453
Create Date: 2023-09-08 00:44:29.282586+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caeb376180e0'
down_revision = '2c5e28ff2453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
