"""add columns

Revision ID: ff00777dc3bc
Revises: 16a7079c1f19
Create Date: 2023-09-06 11:57:12.703117+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff00777dc3bc'
down_revision = '16a7079c1f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_login_id_key', 'users', type_='unique')
    op.drop_column('users', 'login_id')
    op.drop_column('users', 'password')
    op.drop_column('users', 'name')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('login_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_login_id_key', 'users', ['login_id'])
    # ### end Alembic commands ###
