"""add columns

Revision ID: 6fd0af28f6ca
Revises: ff00777dc3bc
Create Date: 2023-09-06 12:01:09.126918+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd0af28f6ca'
down_revision = 'ff00777dc3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
